### PR TITLE
Update to `generated by rust-bindgen 0.69.2` in `native.rs`

### PR DESCRIPTION
**Pull request by fornwall**
Fixes the below CI failure:

> Error: Generated files are different, please regenerate with cargo run -p generator!
> diff --git a/ash/src/vk/native.rs b/ash/src/vk/native.rs
> index 223fb73..f28431a 100644
> --- a/ash/src/vk/native.rs
> +++ b/ash/src/vk/native.rs
> @@ -1,4 +1,4 @@
> -/* automatically generated by rust-bindgen 0.69.1 */
> +/* automatically generated by rust-bindgen 0.69.2 */
>
> #[repr(C)]
> #[derive(Copy, Clone, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]

### CODE REVIEW

**Comment by MarijnS95** [comment]
The right fix should be affixing the bindgen version in `Cargo.toml`, so that we don't run into such spurious and unnecessary failures again.

`dependabot` can point out updates for us.

**Comment by fornwall** [comment]
> The right fix should be affixing the bindgen version (bindgen = "=0.69.2") in generator/Cargo.toml, so that we don't run into such spurious and unnecessary failures again.

@MarijnS95 Makes sense - done that in 6172fa72ce1242c512481e98592e735eafed6d0e now.

**Review by MarijnS95 — APPROVED** [review]

**Review by Ralith — APPROVED** [review]

**Comment by Ralith** [comment]
Might benefit from a comment explaining why it's pinned.

**Comment by fornwall** [comment]
> Might benefit from a comment explaining why it's pinned.

@Ralith Thanks - done in
317c2dfb292eecffdb175d128676f69803e3586d.

**Pull request merged**
