### PR TITLE
extensions/khr: Add VK_KHR_external_fence_capabilities, VK_KHR_external_semaphore_capabilities and VK_KHR_external_memory_capabilities

### PR DESCRIPTION
**Pull request by i509VCB**

### CODE REVIEW

**Review by Ralith — COMMENTED** [review]
These bindings seem fine, but are you sure you need them? They were all promoted to core in 1.1.

**Comment by i509VCB** [comment]
I just added these in case someone needs these in Vulkan 1.0

**Comment by MarijnS95** [comment]
Doesn't seem worth the maintenance effort if no one is actively using these, unlike the other wrappers TBH.

**Comment by Ralith** [comment]
Yeah, let's hold off unless there's specific demand, but thanks for the contribution!

**Pull request closed without merging**
